# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# SUITABLE_SNPRINTF_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set SUITABLE_SNPRINTF_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# SUITABLE_SNPRINTF_EXITCODE__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set SUITABLE_SNPRINTF_EXITCODE__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The SUITABLE_SNPRINTF_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/hzm/002-work/tcpdump-4.99.5/jgb.build/CMakeFiles/CMakeTmp/src.c
# Executable    : /home/hzm/002-work/tcpdump-4.99.5/jgb.build/CMakeFiles/cmTC_afa92-SUITABLE_SNPRINTF_EXITCODE
# Run arguments : 
#    Called from: [3]	/usr/share/cmake-3.22/Modules/Internal/CheckSourceRuns.cmake
#                 [2]	/usr/share/cmake-3.22/Modules/CheckCSourceRuns.cmake
#                 [1]	/home/hzm/002-work/tcpdump-4.99.5/CMakeLists.txt

set( SUITABLE_SNPRINTF_EXITCODE 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( SUITABLE_SNPRINTF_EXITCODE__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)

